#define __EMBED__ 1
#include "Falloc.cu"
#include "Regex.1\Regex.cu"
#include "Runtime.cu"
#include "Runtime+Alloc.cu"
#include "Runtime+BenignAlloc.cu"
#include "Runtime+Mem0.cu"
#include "Runtime+Mem1.cu"
#include "Runtime+Mutex-noop.cu"
#include "Runtime+Mutex-gpu.cu"
#include "Runtime+Status.cu"
#include "RuntimeOS.cu"
#include "RuntimeOS+FileSystem.cu"
