//#include "dos.cu"
#include "noextensions.cu"
#include "readdir.cu"
//#include "regex_compat.cu"
//#include "tclalloc.cu"
#include "tclAssem.cu"
#include "tclBasic.cu"
#include "tclCmdAH.cu"
#include "tclCmdIL.cu"
#include "tclCmdMZ.cu"
#undef STATIC_SIZE
//#include "tclEmbed.cu" -- Test Driver
//#include "tclEnv.cu"
#include "tclExpr.cu"
#include "tclGet.cu"
#include "tclGlob.cu"
#include "tclHash.cu"
#include "tclHistory.cu"
//#include "tclLoad.cu"
//#include "tclLoadDl.cu"
//#include "tclmod.cu"
#include "tclParse.cu"
#include "tclProc.cu"
//#include "tclTest.cu" -- Test Driver
#include "tclUnixAZ.cu"
#include "tclUtil.cu"
//#include "tcluxstr.cu"
//#include "tcluxutl.cu"
#include "tclVar.cu"
#include "tclXdbg.cu"
#include "tclXgen.cu"
#include "tinytcl.cu" -- Test Driver